name: Manual Build and Release
on: [workflow_dispatch]
jobs:
  example:
    name: Build Flutter APKs
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./okaki
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./okaki/build/app/outputs/flutter-apk/*.apk"
          tag: v0.1.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
